### ISSUE TITLE
Prompt reward text

### ISSUE THREAD

**Issue by salavesca** [Ziiven/flarum-daily-check-in#1]
Requires the antoinefr/flarum-ext-money extension

Example: Gained [reward] reward

If we type Gained [reward] reward, back in antoinefr extension we have 

Name of the money (ex: [money] points) 
Balance: $ [money] 

So it prompts gained $ 0. 

For now i am using: 
Example: Gained [reward] reward

Gained $0.05 reward (just as a text that may have to be changed regularly) 

Thanks
I also have a proposal, if you can create an extension for share buttons that will display under discussions after like - reply. (Users can pick/choose the buttons they want to use)

Share discussion
![buttons](https://user-images.githubusercontent.com/85366054/192641640-88799252-7f64-4779-80dc-cd967551e1ab.png)

**Comment by Ziiven** [comment]
Just fixed this bug, thanks for reporting 😃

I'll think about your proposal, but I cannot guarantee that I can do it since I'm not fully familiar with building extension.
